<<child='../s00-includes/include-01-preambule-open.Rnw'>>=
@

<<child='../s00-includes/include-02-use-packages.Rnw'>>=
@

<<child='../s00-includes/include-03-beamer-setup.Rnw'>>=
@
%\setbeameroption{show notes}
%\setbeameroption{show notes on second screen}

<<child='../s00-includes/include-04-course-info.Rnw'>>=
@

	\subtitle{Session 1: Course Overview}
	\date{}

\begin{document}
<<reset-ws, echo=F>>=
	rm(list=ls())
@

<<r-setup, include=FALSE, cache=FALSE>>=
  library(knitr)
  library(xtable)
  options(width = 60)
  opts_chunk$set(tidy = TRUE, size='small')
  options(max.print=10)
  options(digits=4)
  options(xtable.comment = FALSE)
@
	\maketitle

\section*{Outline}
	\frame{
	    \small
			\frametitle{Outline}
			%\begin{multicols}{2}
			    \tableofcontents[hideallsubsections]
		   %\end{multicols}
		}
		
% The course materials here
\section*{Acknowledgement}
	  \begin{frame}{Acknowledgement}
		  \vfill
		  \centering
 			 \begin{beamercolorbox}[sep=8pt,center,shadow=true,rounded=true]{title}
 				\usebeamerfont{title}When not specifically cited, the contents of this presentation are adapted from \cite{forouzan2012data}.%
			  \end{beamercolorbox}
		  \vfill
	  \end{frame}
	  
\section{Course Details}
		<<course-overview, child='s01-rnw/s01-introduction.Rnw'>>=
		@

\section{Review: Data Communications and Networking}
	<<0001-data-communications-introduction, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0001-data-communications-introduction.Rnw'>>=
	@
	
	\subsection{Data Communications}
		<<0002-data-communications-definitions-and-characteristics, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0002-data-communications-definitions-and-characteristics.Rnw'>>=
		@
			
	\subsection{Networks}
		<<0006-networks-intro, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0006-networks-intro.Rnw'>>=
		@	
		<<0007-networks-criteria, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0007-networks-criteria.Rnw'>>=
		@
		<<0008-networks-physical-structure, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0008-networks-physical-structure.Rnw'>>=
		@
		<<0009-networks-types, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0009-networks-types.Rnw'>>=
		@
	
	\subsection{TCP/IP Protocol Suite}
		<<0105-tcp-ip-protocol-suite-intro, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0105-tcp-ip-protocol-suite-intro.Rnw'>>=
		@
		<<0106-tcp-ip-protocol-suite-layers, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0106-tcp-ip-protocol-suite-layers.Rnw'>>=
			@
<<0108-layered-arch-operation, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0108-layered-arch-operation.Rnw'>>=
		@

\section{Review: Physical Layer}
	<<0301-phy-intro, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0301-phy-intro.Rnw'>>=
	@
		
	\subsection{Transmission Medium}
		<<0302-phy-transmission-medium, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0302-phy-transmission-medium.Rnw'>>=
		@
		
	\subsection{Data and Signals}
		<<0303-phy-data-and-signals, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0303-phy-data-and-signals.Rnw'>>=
		@
		
	\subsection{Periodic Analog Signals}
		<<0304-phy-periodic-analog-signals, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0304-phy-periodic-analog-signals.Rnw'>>=
		@
	
	\subsection{Digital Signals}
		<<0305-phy-digital-signal, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0305-phy-digital-signal.Rnw'>>=
		@
		
	\subsection{Transmission Impairments}
		<<0306-phy-transmission-impairment, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0306-phy-transmission-impairment.Rnw'>>=
		@

	\subsection{Data Rate Limits}
		<<0307-phy-data-rate-limits, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0307-phy-data-rate-limits.Rnw'>>=
		@
			
	\subsection{Performance}
		<<0308-phy-performance, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0308-phy-performance.Rnw'>>=
		@

\section{Exercise}
		<<0309-phy-exercise, child='/home/daniel/Documents/My Lectures/materials-library/dcn-related-contents/Rnw-sources/0309-phy-exercise.Rnw'>>=
		@

\section*{Next Week}
		<<next-week, child='s01-rnw/s02-next-week.Rnw'>>=
		@
			
% Closing document
<<child='../s00-includes/include-99-master-footer.Rnw'>>=
@
